### ISSUE TITLE
some questions of output files

### ISSUE THREAD

**Issue by Axolotl233** [Nextomics/NextDenovo#11]
Hello, I m an ungreatute of lifescience institute, Lanzhou University. my name is Wenjie

I have tested your tools using some public data yesterday. It is amazing that the running speed of NextDenovo so fast, but after program processing, I have some questions confused

first is I do not know which is assembled most properest seqence, there have nine output directories of 02.cns_algin,please tell me how to selcet best and what are the differents among its.

secord is the folder named 03.ctg_graph is empty, whether I made some mistakes when I run program or input is improper. And what is means of 'graph' in thrid step, How is it different from 'assembly'?

my test data is ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR217/003/ERR2173373/ERR2173373.fastq.gz
and my deploy file was uploaded in appendix.

all best.
[runcfg.txt](https://github.com/Nextomics/NextDenovo/files/3613438/runcfg.txt)

**Comment by moold** [comment]
Hi, Currently,  we did not release the assembly module because of some reasons, you only can use NextDenovo to do error correction, and use the corrected seeds/reads as input for other assemblers, such as [WTDBG](https://github.com/ruanjue/wtdbg).
BTW, all files in 02.cns_align/01.get_cns.sh.work/get_cns*/cns.fasta are the corrected data, you need merge these files.
