### ISSUE TITLE
Publication plan

### ISSUE THREAD

**Issue by rkajitani** [Nextomics/NextDenovo#148]
This is not a technical issue. NextDenovo outperformed other tools for several PacBio-CLR data of ours, and I want to adopt this tool in the associated projects.
Is there a preprint or document describing the algorithm of NextDenovo? Or, I'd be pleased if I could know the rough schedule for the publication. These will be helpful for me in persuading the project members. Thank you for developing the impressive tool!

Rei Kajitani

**Comment by moold** [comment]
Hi, first, thank you very much for your support. Unfortunately, there is no public preprint or document describing the algorithm by now. But, [here](https://nextdenovo.readthedocs.io/en/latest/TEST3.html) are some benchmark results. Since I work in a company and have a lot of daily work, so I do not have much time to prepare the NextDenovo paper, but I am still working on it and plan to publish it in this year.

**Comment by rkajitani** [comment]
Thank you for the reply and the benchmark results. I am really looking forward to your paper (including preprint)!
