### ISSUE TITLE
How to run nextdenovo on a set of cloud service with SGE?

### ISSUE THREAD

**Issue by Zea1nfO** [Nextomics/NextDenovo#77]
**Question or Expected behavior**
Hi sir
i wanna run nextdenovo on a cloud service and  i set the parameter in my run.cfg like this to run the test file:

**job_type = sge
cluster_options = -l vf={vf} -pe smp {cpu} -S {bash} -w n
sge_queue = "the node name given by the cloud service company"**

The first split job is good to submit and excute, but the second step`s align jobs just stuck there. 
when i type qstat , then the state always show as "qw".
how can solve this?

**Operating system**
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804
Codename:	Core

**GCC**
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Python**
Python 3.7.3

**NextDenovo**
nextDenovo v2.3.0

**Additional context** (Optional)
None

**Comment by Zea1nfO** [comment]
besides ,if i type "qhost -q", i will got several nodes.
but i just wanna use one of them to excute my jobs.
so how can i custom my run.cfg file.
thanks a lot
:)

**Comment by moold** [comment]
The qw state means your jobs are queued and waiting, you can  use `qstat -j PID` to check. For NextDenovo, see [here](https://github.com/moold/ParallelTask) to instlal drmaa, and then set `job_type = sge` is ok, you also can adjust `cluster_options` to meet your requirement.  If you still have problems, you need to ask your system administrator for help, which is usually caused by incorrect SGE system configuration.
